[[headers]]
for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1;mode=block"
    X-Content-Type-Options = "nosniff"
    Content-Security-Policy = "script-src 'self' assets.calendly.comù; base-uri 'self';"
    
[[headers]]
for = "/assets/*"
    [headers.values]
      cache-control = "max-age=2592000"
